[workspace]
git_release_enable = true   # Create a git release for the created tag
git_tag_enable = true       # Create a git tag for the new package version
pr_labels = ["release"]     # Add the `release` label to the release PR
pr_draft = true             # Create release PR as a draft
release = false             # Disable release-plz for the workspace
publish = false             # Disable `cargo publish` for the workspace

[[package]]
name = "graphql-toolkit"
release = true          # Enable release-plz for the package

[[package]]
name = "graphql-toolkit-ast"
release = true          # Enable release-plz for the package

[[package]]
name = "graphql-toolkit-value"
release = true          # Enable release-plz for the package
