[package]
name = "graphql-toolkit-value"
description = "GraphQL Toolkit value definitions"
version = "0.0.0"
edition = "2021"
authors = ["Lorenzo Delgado (LNSD) <lnsdev@proton.me>"]
license = "Apache-2.0"
rust-version = "1.71.1"
