[workspace]
resolver = "2"
members = [
    "graphql-toolkit",
    "graphql-toolkit-ast",
    "graphql-toolkit-composer",
    "graphql-toolkit-http",
    "graphql-toolkit-parser",
    "graphql-toolkit-value",
    "graphql-toolkit-writer",
    "testlib/parser-testdata",
]
